name: lifecycle
description: A flutter package that let you easily add hooks for widget lifecycle.
version: 0.9.0
homepage: https://github.com/chenenyu/lifecycle
topics:
  - lifecycle
  - navigator-observer
  - app-lifecycle-state
  - lifecycle-listener
  - widgets-lifecycle

environment:
  flutter: ">=3.13.0"
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
